DROP DATABASE IF EXISTS basketballDB;
CREATE DATABASE basketballDB;
USE basketballDB;

CREATE TABLE player(
    player_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    fName VARCHAR(40),
    lName VARCHAR(40),
    CONSTRAINT pk_player PRIMARY KEY (player_id)
);


CREATE TABLE team(
    team_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    team VARCHAR(70),
    CONSTRAINT pk_team PRIMARY KEY (team_id)
);


CREATE TABLE divison(
    divison_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    divison VARCHAR(40),
    CONSTRAINT pk_divison PRIMARY KEY (divison_id)
);


CREATE TABLE franchise(
    franchise_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    title VARCHAR(40),
    player_id SMALLINT UNSIGNED NOT NULL,
    team_id SMALLINT UNSIGNED NOT NULL,
    divison_id SMALLINT UNSIGNED NOT NULL,
    yr_founded YEAR,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_franchise PRIMARY KEY (franchise_id),
    CONSTRAINT fk_player FOREIGN KEY (player_id) REFERENCES player (player_id),
    CONSTRAINT fk_team FOREIGN KEY (team_id) REFERENCES team (team_id),
    CONSTRAINT fk_divison FOREIGN KEY (divison_id) REFERENCES divison (divison_id)
);

ALTER TABLE player
    ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE team
    ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


ALTER TABLE divison
    ADD date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


